name: ExpiryCommand
main: leaderos.web.tr.timed.Main
version: 1.3.1
author: Geik
commands:
  expirycommand:
    description: Ana komuttur.
  kalansorgu:
    description: Ürünlerin kalan süresini gösterir.